name: Build

on:
  # Triggers the workflow on push or pull request events on these branches
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    name: Checkout, install, lint, build and test with coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install node dependencies
        run: npm ci

      - name: Audit dependencies for security vulnerabilities
        run: npm audit

      - name: Lint the source code
        run: npm run-script lint

      - name: Build the source code
        run: npm run-script build

      - name: Execute test coverage
        run: npm run-script test:ci

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: coverage/lcov.info
          fail_ci_if_error: true # optional (default = false)